# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPutPrice <- function(Expiry = 0.75, Strike = 150, Spot = 140, Vol = 0.24, r = 0.07, b = 120, NumberOfPaths = 10000L) {
    .Call(`_putOptionPricer_getPutPrice`, Expiry, Strike, Spot, Vol, r, b, NumberOfPaths)
}

rcpp_hello <- function() {
    .Call(`_putOptionPricer_rcpp_hello`)
}

